#!/usr/bin/env bun
// ═══════════════════════════════════════════════════════════════
//  FAIR RUNNER — Stable Watchdog for the Self-Growing Harness
//
//  ARCHITECTURE (for AI readers):
//    This is the IMMUTABLE SUPERVISOR. fair.ts is the mutable agent
//    harness that the AI can rewrite. This file NEVER touches itself
//    and should NEVER be edited by the AI. It is the safety net.
//
//  DUAL-PROCESS PATTERN:
//    ┌─────────────┐      watches       ┌─────────────┐
//    │  runner     │  ←───────────────  │   fair.ts   │
//    │  (stable)   │   file changes     │ (self-edit) │
//    └──────┬──────┘                    └──────┬──────┘
//           │                                   │
//      validates, snapshots,              edits itself via
//      reverts on failure                 write/edit tools
//
//  HOT-RELOAD PIPELINE (WAIT-FOR-IDLE):
//    1. Watch fair.ts via fs.watch
//    2. Debounce 300ms
//    3. Write .fair/.restart-requested (do NOT kill child yet)
//    4. Child finishes current LLM turn → saves session → exits cleanly
//    5. If child idle at prompt, poller exits within 500ms
//    6. If child stuck, force-kill after 5s fallback
//    7. Validate syntax with Bun.Transpiler
//    8. Run tests (bun test, 30s timeout)
//    9. Pass  → snapshot to .fair/snapshots/ → restart child
//    10. Fail → restore last known good snapshot → inject error
//               into session JSONL → restart child so AI sees it
//
//  SESSION CONTINUITY:
//    - Child always launched with: --resume <active-session-id>
//    - fair.ts auto-saves after every turn
//    - On restart, child loads the same session seamlessly
//
//  CRASH-LOOP GUARD:
//    If >3 restarts occur within 15s, we pause to prevent infinite
//    loops. The user must fix fair.ts manually and save again.
//
//  DO NOT EDIT THIS FILE FROM WITHIN THE AI HARNESS.
// ═══════════════════════════════════════════════════════════════

import { watch, unlinkSync } from "fs";
import { readdir, stat, readFile, writeFile, copyFile, mkdir } from "fs/promises";
import { join } from "path";

const SESSION_FILE = ".fair/active-session";
const SNAPSHOT_DIR = ".fair/snapshots";

let child: ReturnType<typeof Bun.spawn> | null = null;
let activeSession: string;
let lastGoodSnapshot: string | null = null;
let restartCount = 0;
let lastRestartTime = 0;
let restartTimer: ReturnType<typeof setTimeout> | null = null;
let isRestoring = false;
let pendingRestart = false;
let forceKillTimer: ReturnType<typeof setTimeout> | null = null;
const RESTART_SENTINEL = ".fair/.restart-requested";

// ── Helpers ──────────────────────────────────────────────────

async function ensureDirs() {
  await mkdir(".fair/sessions", { recursive: true });
  await mkdir(SNAPSHOT_DIR, { recursive: true });
}

async function getActiveSession(): Promise<string> {
  try {
    return (await readFile(SESSION_FILE, "utf8")).trim();
  } catch {
    const id = crypto.randomUUID().slice(0, 8);
    await writeFile(SESSION_FILE, id);
    console.log(`[runner] created session ${id}`);
    return id;
  }
}

async function findLatestSnapshot(): Promise<string | null> {
  try {
    const files = (await readdir(SNAPSHOT_DIR)).filter((f) => f.endsWith(".ts"));
    if (!files.length) return null;
    const withStats = await Promise.all(
      files.map(async (f) => ({
        file: join(SNAPSHOT_DIR, f),
        mtime: (await stat(join(SNAPSHOT_DIR, f))).mtimeMs,
      }))
    );
    withStats.sort((a, b) => b.mtime - a.mtime);
    return withStats[0].file;
  } catch {
    return null;
  }
}

async function snapshotCurrent(): Promise<string> {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const dest = join(SNAPSHOT_DIR, `${ts}-fair.ts`);
  await copyFile("fair.ts", dest);
  lastGoodSnapshot = dest;
  return dest;
}

async function restoreSnapshot(src: string) {
  isRestoring = true;
  await copyFile(src, "fair.ts");
  console.log(`[runner] restored from ${src}`);
  // Give fs.watch a moment to settle so we don't trigger ourselves
  setTimeout(() => {
    isRestoring = false;
  }, 500);
}

async function injectSessionError(error: string) {
  const path = `.fair/sessions/${activeSession}.jsonl`;
  const msg = JSON.stringify({
    role: "user",
    content:
      `[Runner] Your previous edit to fair.ts failed and was automatically reverted.\n\n` +
      `Error:\n${error.slice(0, 800)}\n\n` +
      `Please analyze the error, fix your approach, and try again.`,
  });
  await writeFile(path, msg + "\n", { flag: "a" });
}

function validateSyntax(source: string): { ok: true } | { ok: false; error: string } {
  try {
    const transpiler = new Bun.Transpiler({ loader: "ts" });
    transpiler.transformSync(source);
    return { ok: true };
  } catch (e: any) {
    return { ok: false, error: `Syntax error: ${e.message}` };
  }
}

async function runTests(): Promise<{ ok: true } | { ok: false; error: string }> {
  console.log("[runner] running tests...");
  const proc = Bun.spawn(["bun", "test"], { stdout: "pipe", stderr: "pipe" });
  const timer = setTimeout(() => proc.kill("SIGKILL"), 30000);
  const exitCode = await proc.exited;
  clearTimeout(timer);

  const stderr = await new Response(proc.stderr).text();
  const stdout = await new Response(proc.stdout).text();

  if (exitCode !== 0) {
    const out = stderr || stdout;
    return { ok: false, error: `Tests failed (exit ${exitCode}):\n${out}`.slice(0, 600) };
  }
  return { ok: true };
}

// ── Child lifecycle ──────────────────────────────────────────

function startChild() {
  console.log(`[runner] spawning: bun fair.ts --resume ${activeSession}`);
  child = Bun.spawn(["bun", "fair.ts", "--resume", activeSession], {
    stdio: ["inherit", "inherit", "inherit"],
  });

  const thisChild = child;
  thisChild.exited.then(async (code) => {
    if (child !== thisChild) return; // this child was replaced by a newer one
    if (pendingRestart) {
      pendingRestart = false;
      try { unlinkSync(RESTART_SENTINEL); } catch {}
      await runRestartPipeline("fair.ts changed");
    } else {
      console.log(`[runner] child exited with code ${code}`);
      // Clean exit (user typed /quit) — runner shuts down too
      if (code === 0) {
        console.log("[runner] shutting down...");
        try { unlinkSync(RESTART_SENTINEL); } catch {}
        process.exit(0);
      }
    }
  });
}

async function killChild() {
  if (!child) return;
  child.kill("SIGINT");
  const exited = Promise.race([
    child.exited,
    new Promise<void>((_, reject) => setTimeout(() => reject(new Error("timeout")), 3000)),
  ]);
  try {
    await exited;
  } catch {
    console.log("[runner] child did not exit gracefully, killing");
    child.kill("SIGKILL");
    try {
      await child.exited;
    } catch {}
  }
  child = null;
}

async function requestRestart(reason: string) {
  if (pendingRestart) return;
  pendingRestart = true;
  await writeFile(RESTART_SENTINEL, "");
  console.log(`[runner] restart requested — waiting for child to finish current turn...`);

  // Force-kill fallback if child doesn't exit gracefully within 5s
  forceKillTimer = setTimeout(async () => {
    if (pendingRestart && child) {
      console.log("[runner] child did not exit gracefully, forcing restart");
      pendingRestart = false;
      await killChild();
      try { unlinkSync(RESTART_SENTINEL); } catch {}
      await runRestartPipeline(reason);
    }
  }, 5000);
}

async function runRestartPipeline(reason: string) {
  console.log(`\n[runner] restart triggered: ${reason}`);

  // Crash-loop guard
  const now = Date.now();
  if (now - lastRestartTime < 15000) {
    restartCount++;
    if (restartCount >= 3) {
      console.error(
        "[runner] too many restarts in 15s — pausing. fix fair.ts manually, then save again."
      );
      return;
    }
  } else {
    restartCount = 1;
  }
  lastRestartTime = now;

  if (forceKillTimer) {
    clearTimeout(forceKillTimer);
    forceKillTimer = null;
  }

  // Validate
  const source = await readFile("fair.ts", "utf8");
  const syntax = validateSyntax(source);
  if (!syntax.ok) {
    console.error(`[runner] ${syntax.error}`);
    if (lastGoodSnapshot) {
      await restoreSnapshot(lastGoodSnapshot);
      await injectSessionError(syntax.error);
    }
    startChild(true);
    return;
  }

  const tests = await runTests();
  if (!tests.ok) {
    console.error(`[runner] ${tests.error}`);
    if (lastGoodSnapshot) {
      await restoreSnapshot(lastGoodSnapshot);
      await injectSessionError(tests.error);
    }
    startChild(true);
    return;
  }

  // All good — snapshot and start
  const snap = await snapshotCurrent();
  console.log(`[runner] validated & snapshotted → ${snap}`);
  startChild(true);
}

// ── Main ─────────────────────────────────────────────────────

async function main() {
  await ensureDirs();
  activeSession = await getActiveSession();

  const latest = await findLatestSnapshot();
  if (latest) {
    lastGoodSnapshot = latest;
  } else {
    lastGoodSnapshot = await snapshotCurrent();
  }

  startChild();

  // Watch fair.ts for changes
  const watcher = watch("fair.ts", (eventType) => {
    if (eventType !== "change") return;
    if (isRestoring) return;
    if (restartTimer) clearTimeout(restartTimer);
    restartTimer = setTimeout(() => {
      restartTimer = null;
      requestRestart("fair.ts changed");
    }, 300);
  });

  process.on("SIGINT", async () => {
    console.log("\n[runner] shutting down...");
    watcher.close();
    await killChild();
    process.exit(0);
  });
}

main();
